config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { registrations: 'registrations' } do
        get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    end
    devise_scope :user do
        get '/sign-in' => "devise/sessions#new", :as => :login
    end
    get '/users/:id', :to => 'users#show', :as => :user
    resources :users, only: [:index]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :adventures do
      resources :comments
      collection do
          get 'mytwigs'
      end
    end
    resources :chat_rooms, only: [:new, :create, :show, :index] do
        post "/create_message", :to => "chat_rooms#create_msg", :as => "create_msg"
    end
    root :to => redirect('/adventures')
    resources :friendships
    resources :users
    mount ActionCable.server => '/cable'
  end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
    def index
        @chat_rooms = ChatRoom.all
        @my_chat_rooms = ChatRoom.where(host_id: current_user.id).or(ChatRoom.where(user_id: current_user.id))
    end
    
    def create
        @chat_room = current_user.chat_rooms.build(params[:host_name])
    
        if @chat_room.save
            flash[:success] = 'Chat added!'
            redirect_to @chat_room
            else
            render 'new'
        end
    end
    
    def create_msg
        @user1 = User.find(ChatRoom.find(params[:chat_room_id]).host_id)
        @user2 = User.find(ChatRoom.find(params[:chat_room_id]).user_id)
        msg = ChatRoom.find(params[:chat_room_id]).messages.build(body: params[:message][:body], user: current_user)
        msg.save
        if current_user.id == @user2.id
            UserMailer.welcome_email(@user1, @user2, msg).deliver
            else
            UserMailer.welcome_email(@user2, @user1, msg).deliver
        end
        redirect_to chat_room_path(params[:chat_room_id])
    end
    
    def show
        @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
        @message = Message.new
        @user1 = User.find(@chat_room.host_id)
        @user2 = User.find(@chat_room.user_id)
    end
    
    private
    
end

app/views/chat_rooms/_chat_room.html.haml
%li= link_to "#{chat_room.user.first_name}", chat_room_path(chat_room)

app/views/chat_rooms/index.html.haml
:css
  .messagestitle {
    text-transform: uppercase;
    font-size: 33px;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    position: absolute;
    left: 498px;
    top: 122px;
  }

   .titleline {
    clear: both;
    float:none;
    display:block;
    position: relative;
    top: 54px;
    left: 501px;
    width: 520px;
    border:none;
    border-top:1px black;
    color: black;
    background-color: black;
    height:1px;
    z-index:99;
  }
  .container {
    position: absolute;
    left: 501px;
    top: 165px;
    width: 520px;
    height: 350px;
    z-index: 200;
    background-color: white;
    overflow-y: scroll;
    overflow-x: hidden;
  }

  .singularchat {
    position: relative;
    left: -5px;
    top: 10px;
    width: 518px;
    height: 30px;
    z-index: 200;
    margin: -10px;
    padding:10px;
    float:left;
  }

  .name {
    position: relative;
    left: 9px;
    top: -14px;
    color: black;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    font-size: 12px;
    z-index: 300;
    margin: 0px;
    padding:0px;
    float:left;
  }

  .avatar {
    position: relative;
    width: 32px;
    height: 32px;
    top: -10px;
    z-index: 300;
    margin: 0px;
    padding: 0px;
    float:left;
  }

  .last_message_at {
    z-index: 100;
    position: relative;
    left: -13px;
    top: 6px;
    margin: 0px;
    padding: 0px;
    float:left;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    font-size: 12px;
  }

  .last_message_text {
    position: absolute;
    z-index: 100;
    width: 320px;
    height: 37px;
    top: -4px;
    left: 120px;
    margin-right: -2000px;
    float:left;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    font-size: 12px;
    line-height: 19px;
    overflow: hidden;


  }

  .dividingline {
    clear: both;
    float:none;
    display:block;
    position: relative;
    top: -10px;
    left: 25px;
    width: 520px;
    border:none;
    color: black;
    background-color: black;
    height:1px;
    z-index:99;
  }

  .box {
    position: relative;
    left: -15px;
    width: 518px;
    height: 30px;
    z-index: 200;

    margin-bottom: 20px;
  }

  .adventureprice {
    position: absolute;
    left: 450px;
    z-index: 100;
    float: left;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    font-size: 12px;
  }
.messagestitle
  Messages
.titleline
.container
  - @my_chat_rooms.sort {|a,b| b.created_at <=> a.created_at }.each do |c|
    -if c.user_id == current_user.id
      .box
        %a.singularchat{:href => chat_room_path(c.id)}
        .avatar{:style => "z-index: 400"}
          %img{:href => user_path(c.host_id), :src => "/assets/logos/user.png", :width => "30", :style => "z-index: 400" }
        .name
          #{User.find(c.host_id).first_name}
        -if c.messages.last
          .last_message_at
            #{local_time(c.messages.order("created_at").last.timestamp, format: '%b %e, %Y')}
        .adventureprice
          $ #{Adventure.find(c.adventure).price}
        -if c.messages.last
          .last_message_text
            #{c.messages.order("created_at").last.body}

      .dividingline
    -else
      .box
        %a.singularchat{:href => chat_room_path(c.id)}
        .avatar{:style => "z-index: 400"}
          %img{:href => user_path(c.user_id), :src => "/assets/logos/user.png", :width => "30", :style => "z-index: 400"}
        .name
          #{User.find(c.user_id).first_name}
        -if c.messages.last
          .last_message_at
            #{local_time(c.messages.order("created_at").last.timestamp, format: '%b %e, %Y')}
        .adventureprice
          $ #{Adventure.find(c.adventure).price}
        -if c.messages.last
          .last_message_text
            #{c.messages.order("created_at").last.body}
      .dividingline

app/views/chat_rooms/new.html.haml
%h1 Choose a Name for your Adventure
= form_for @chat_room do |f|
  .form-group
    = f.label :title
    = f.text_field :title, autofocus: true, class: 'form-control'
  = f.submit "Add!", class: 'btn btn-primary'

app/views/chat_rooms/show.html.haml
:css
  .messagebox {
    position: absolute;
    left: 501px;
    top: 165px;
    width: 520px;
    height: 350px;
    z-index: 200;
    background-color: white;
    overflow-y: scroll;
    overflow-x: hidden;
  }
  .newmessage {
    position: absolute;
    top: 400px;
  }
  .messagestitle {
    text-transform: uppercase;
    font-size: 33px;
    position: absolute;
    left: 498px;
    top: 122px;
  }

  .titleline {
    clear: both;
    float:none;
    display:block;
    position: relative;
    top: 54px;
    left: 501px;
    width: 520px;
    border:none;
    border-top:1px black;
    color: black;
    background-color: black;
    height:1px;
    z-index:99;
  }

  .formcontrol {
    position: fixed;
    z-index: 200;
    height: 68px;
    top: 515px;
    left: 541px;
    width: 480px;
    padding: 5px 10px;
    -webkit-appearance: none;
    display: inline-block;
    border: 1px solid black;
    border-radius: 0px;
    box-sizing: border-box;
    color: black;
    resize: none;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    font-size: 90%;
  }
  .subbutton {
    position: fixed;
    left: 901px;
    top: 588px;
    height: 30px;
    width: 120px;
    padding: 5px;
    -webkit-appearance: none;
    margin: 5px 0;
    display: inline-block;
    border: 1px solid black;
    border-radius: 0px;
    box-sizing: border-box;
    color: black; !important;
    resize: none;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    font-size: 13px;
    background-color: #D9F0FD;
    z-index: 200;
  }

  .subbutton:hover {
    background-color: #BEE5FB;
    z-index: 200;
  }

-if !current_user
  %a{:href => adventures_path, :style => "position: relative; left: 500px; top: 400px; font-size: 33px;"} Please log in first
-else
  .messagestitle
    - if current_user.id == @user1
      MESSAGES WITH #{@user2.first_name}
    -else
      MESSAGES WITH #{@user1.first_name}
  .titleline
  .messagebox
    = render @chat_room.messages
  .newmessage
    = form_for @message, url: chat_room_create_msg_path(@chat_room.id) do |f|
      .form-group
        = f.text_area :body, class: 'formcontrol', :required => 'required'
      %button.accept{:class => "subbutton"}
        SEND MESSAGE