config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { registrations: 'registrations' } do
        get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    end
    devise_scope :user do
        get '/sign-in' => "devise/sessions#new", :as => :login
    end
    get '/users/:id', :to => 'users#show', :as => :user
    resources :users, only: [:index]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :adventures do
      resources :comments
      collection do
          get 'mytwigs'
      end
    end
    resources :chat_rooms, only: [:new, :create, :show, :index] do
        post "/create_message", :to => "chat_rooms#create_msg", :as => "create_msg"
    end
    root :to => redirect('/adventures')
    resources :friendships
    resources :users
    mount ActionCable.server => '/cable'
  end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :adventure
    belongs_to :user
    mount_uploaders :image, ImageUploader
    serialize :image, JSON
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @adventure = Adventure.find(params[:adventure_id])
        @comment = @adventure.comments.create(params[:comment].permit(:name, :body, :capabilities, :price, :image))
        @comment.user_id = current_user.id
        @name = @comment.user.first_name
        @comment.save
        @user1 = @adventure.user
        @user2 = current_user
        UserMailer.comment_email(@user1, @user2, @comment).deliver
        redirect_to adventures_path
    end
    def destroy
        @adventure = Adventure.find(params[:adventure_id])
        @comment = @adventure.comments.find(params[:id])
        @comment.delete
        redirect_to adventures_path
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
%meta{:charset => "utf-8"}/
%script{:src => "https://code.jquery.com/jquery-3.1.1.min.js"}
%link{:href => "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.css", :rel => "stylesheet", :type => "text/css"}/
%script{:src => "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"}
%script{:src => "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.js"}
:css
  .mybox {
    position: relative;
    top: -168px;
    left: 0px;
    width: 640px;
    z-index: 200;
    float: left;
    margin-bottom: 0px;
    padding-top: 10px;
    padding-bottom: -20px;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    font-size: 12px;
  }
  .upperline {
    width: 640px;
    position: relative;
    left: 0px;
    top: -168px;
    border:none;
    border-top:1px black;
    margin-top: 32px;
    color: black;
    background-color: black;
    height:1px;
    padding-top: -10px;
    z-index:99;
    float: left;
  }
  .username {
    font-family: 'pproxima_nova_ltthin', sans-serif;
    font-size: 12px;
    position: absolute;
    left: 40px;
    float: left;
  }
  .avatarka {
    width: 32px;
    height: 32px;
    top: -10px;
    z-index: 300;
    margin: 0px;
    padding: 0px;
    float: left;
  }
  .commentbodymessage {
    position: relative;
    top: 8px;
    left: -1px;
    width: 640px;
    z-index: 200;
    min-height: 30px;
    background-color: white;
    padding-top: 5px;
    padding-left: 10px;
    padding-right: 10px;
    margin-bottom: -10px;
    float: left;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    font-size: 12px;
    border: 1px solid black;
  }

  button.choosethisguide {
    position: relative;
    left: -16px;
    top: 13px;
    height: 30px;
    width: 120px;
    -webkit-appearance: none;
    margin-top: 15px;
    margin-bottom: -10px;
    display: inline-block;
    border: 1px solid black;
    padding-top: 5px;
    text-align: center;
    border-radius: 0px;
    box-sizing: border-box;
    color: black;
    resize: none;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    font-size: 12px;
    background-color: #d9f0fd;

    z-index: 400;
    float: left;
  }

  button.choosethisguide:hover {
    background-color: #bee5fb;
  }

  button.accept {
    position: relative;
    left: -16px;
    top: 13px;
    height: 30px;
    width: 120px;
    -webkit-appearance: none;
    margin-top: 15px;
    margin-bottom: -10px;
    display: inline-block;
    border: 1px solid black;
    padding-top: 5px;
    text-align: center;
    border-radius: 0px;
    box-sizing: border-box;
    color: black;
    resize: none;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    font-size: 12px;
    background-color: #d9f0fd;

    z-index: 400;
    float: left;
  }

  button.accept:hover {
    background-color: #bee5fb;
  }

  .linetogg {
      position: relative;
      top: 30px;
      left: -10px;
      width: 638px;
      border:none;
      border-top:1px black;
      color: black;
      background-color: black;
      height:1px;
      z-index:99;
  }


:javascript
  $(document).ready(function(){
    $(".mymodalg").click(function(){
    $(this).parent().children('.ui.container').children('.ui.modal').modal('show');
    });
  });

  $(document).ready(function(){
    $(".close").click(function(){
    $(this).parent().parent().parent().children('.ui.modal').modal('hide');
    });
  });

  $('.offline').click(function(){
    $(this).parent().children('form').children('.count').val('1');
    $(this).parent().children('.ifpaypal').css('z-index', '3');
    $(this).parent().children('.ifinperson').css('z-index', '1');
  });

  $('.offline').click(function(){
    $(this).parent().children('.ifpaypal').css('z-index', '1');
    $(this).parent().children('.ifinperson').css('z-index', '3');
  });

  $('.online').click(function(){
    $(this).parent().children('form').children('.count').val('0');
    $(this).parent().children('.ifpaypal').css('z-index', '3');
    $(this).parent().children('.ifinperson').css('z-index', '1');
  });


%body{:style => "margin-bottom: 0px;"}
  .upperline
  .mybox
    .avatarka
      %img{:src => "/assets/logos/user.png", :width => "30"}
    .username
      #{link_to "#{comment.user.first_name}", user_path(comment.user.id)} from #{comment.user.city_of_residence} answered #{time_ago_in_words(local_time(comment.created_at))} ago:
    .commentbodymessage
      = comment.body
    - if user_signed_in?
      .dropdown{:style => "margin-bottom: 0px; float: left"}
        %a.dropdown-toggle{"data-toggle" => "dropdown", :type => "button", :style => "padding: 0px; cursor: pointer; z-index: 500; position: relative; float: left; top: 30px; left: 622px;"}
          %img{:src => "/assets/logos/dots.png", :width => "15", :style => "margin-bottom: 14.5px; float: left"}/
        - if (comment.user_id == current_user.id) && comment.adventure.completed != true
          .dropdown-menu.ooooo{"aria-labelledby" => "dropdownMenuButton", :style => "position: absolute; top: 100px; z-index: 1000; left: 470px; -webkit-appearance: none; margin: 5px 0; border-radius: 0px; box-sizing: border-box;   width: 60px; color: black; resize: none; font-family: 'pproxima_nova_ltthin', sans-serif; font-size: 14px;"}
            = link_to 'DELETE COMMENT', [comment.adventure,comment], method: :delete, :style=>'color:black; margin-left: 20px; text-align: center; float: left; width: 60px;',data: { confirm: 'Are you sure?' }
        .dropdown-menu.ooooo{"aria-labelledby" => "dropdownMenuButton", :style => "position: absolute; left: 470px; top: 70px; -webkit-appearance: none; margin: 5px 0; border-radius: 0px; box-sizing: border-box;   width: 60px; color: black; resize: none; font-family: 'pproxima_nova_ltthin', sans-serif; font-size: 14px;"}
          = link_to "REPORT", [comment.adventure,comment], :style=>'color:black; margin-left: 40px; left: 470px; position: text-align: center; float: left; width: 60px;'
    - if user_signed_in?
      - if comment.user.id != current_user.id && comment.user.id != comment.adventure.user.id && current_user.id == comment.adventure.user.id && comment.adventure.completed != true
        .mymodalg{:style => "margin-bottom: 0px; float: left"}
          %button.choosethisguide CHOOSE & PAY
        .ui.container{:style => ""}
          .ui.modal{:close => "CloseModal()", :style => "padding-top:0px; margin-top: 10px; height: 355px; width: 660px; float: left -webkit-appearance: none; margin-bottom: 0px; float: left; position: fixed; top: 10px; left: 810px; border-radius: 0px;"}
            .content
              .close
                %img{:src => "/assets/logos/cancel.png", :width => "15", :style => "float: left; position: relative; left: 0px; top:0px;"}/
              .header{:style => "font-family: 'pproxima_nova_ltthin', sans-serif; font-size: 33px; position: absolute; top: 10px; left: 8px;"}
                CHOOSE PAYMENT METHOD:
              .linetogg
              .bodyparagraph{:style => "font-family: 'pproxima_nova_ltthin', sans-serif; font-size: 14px; position: absolute; top: 58px; left: 10px;"}
                First of all, you need to know that our service is still being tested. There are only friends and friends of our friends here. We hope for your responsibility and honesty. Thank you.
              .secondbody{:style => "font-family: 'pproxima_nova_ltthin', sans-serif; font-size: 14px; position: absolute; top: 110px; left: 10px;"}
                When you choose the payment method and press "Accept" button, you and your TWIGS guide will get each others' private information (mobile and email) and access to chat. This way you can contact with each other and discuss the details.
              .whitebackground{:style => "position: absolute; top: 250px; left: 0px; background-color: white; z-index: 2; height: 100px; width: 660px;"}
              .ifpaypal{:style => "font-family: 'pproxima_nova_ltthin', sans-serif; font-size: 14px; position: absolute; top: 250px; left: 10px; z-index: 3;"}
                You chose PayPal, please transfer your money to our PayPal account: twigs.payments@gmail.com with this note: $#{comment.adventure.price}0 for #{comment.user.first_name}'s #{comment.adventure.action_adventure} ##{comment.adventure.id}
              .ifinperson{:style => "font-family: 'pproxima_nova_ltthin', sans-serif; font-size: 14px; position: absolute; top: 250px; left: 10px;  z-index: 1;"}
                You chose offline method to pay in person. Nice! It's a little old-fashioned but this way we do not take commission from the transaction (for now, lol)
              %input.offline{:onclick => "change()", :type => "button", :value => "PAY IN PERSON", :style => "position: absolute; left: 330px; top: 160px; height: 45px; width: 315px; -webkit-appearance: none; margin-top: 15px; margin-bottom: -10px; display: inline-block; border: 1px solid black; padding-top: 5px; text-align: center; border-radius: 0px; box-sizing: border-box; color: black; resize: none; font-family: 'pproxima_nova_ltthin', sans-serif; font-size: 12px; background-color: white; z-index: 100; float: left"}
              %input.online.mnozstvi_sleva{:type => "button", :value => "PAYPAL", :style => "position: absolute; left: 10px; top:160px; height: 45px; width: 315px; -webkit-appearance: none; margin-top: 15px; margin-bottom: -10px; border: 1px solid black; padding-top: 5px; text-align: center; border-radius: 0px; box-sizing: border-box; color: black; resize: none; font-family: 'pproxima_nova_ltthin', sans-serif; font-size: 12px; background-color: white; z-index: 100; float: left"}
              = form_for :chat_room, method: :post, url: friendships_path, class: 'form'  do |f|
                = f.hidden_field :host_name, value: comment.user.first_name
                = f.hidden_field :friend_id, value: comment.user.id
                = f.hidden_field :adventure_id, value: comment.adventure.id
                = f.hidden_field :method, :class => "count", :value => 0
                %b
                %button.accept{:style => "font-family: 'pproxima_nova_ltthin', sans-serif; font-size: 14px; position: absolute; top: 300px; left: 530px;"}
                  ACCEPT