config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { registrations: 'registrations' } do
        get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    end
    devise_scope :user do
        get '/sign-in' => "devise/sessions#new", :as => :login
    end
    get '/users/:id', :to => 'users#show', :as => :user
    resources :users, only: [:index]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :adventures do
      resources :comments
      collection do
          get 'mytwigs'
      end
    end
    resources :chat_rooms, only: [:new, :create, :show, :index] do
        post "/create_message", :to => "chat_rooms#create_msg", :as => "create_msg"
    end
    root :to => redirect('/adventures')
    resources :friendships
    resources :users
    mount ActionCable.server => '/cable'
  end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
    belongs_to :user
    has_many :comments
    validates :action_adventure, :description, :number_of_people, :city, presence: true
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
    include ActionView::Helpers::NumberHelper
    before_action :correct_user, only: [:destroy]
    before_action :authenticate_user!, only: [:edit, :update, :destroy, :create, :new]
    
    def index
        @search = Adventure.search(params[:q])
        @adventure = Adventure.new
        @adventures = @search.result
        @countries = ISO3166::Country.all
        
    end
    def show
        id = params[:id]
        @adventure = Adventure.find(id)
    end
    def new
        @adventure = Adventure.new
        @adventure.created_at = Time.now
        @countries = ISO3166::Country.all
        # default: render 'new' template
    end
    def create
        params.require(:adventure).permit(:number_of_people,:action_adventure,:country, :city, :description, :details, :adventure_date,:price, :completed)
        if params[:adventure]["adventure_date"] != ""
            format_str = "%m/%d/" + (params[:adventure]["adventure_date"] =~ /\d{4}/ ? "%Y" : "%y")
            date = Date.parse(params[:adventure]["adventure_date"]) rescue Date.strptime(date_str, format_str)
            temp={"number_of_people"=>params[:adventure]["number_of_people"], "action_adventure"=>params[:adventure]["action_adventure"], "country"=>params[:adventure]["country"], "city"=>params[:adventure]["city"], "description"=>params[:adventure]["description"], "details"=>params[:adventure]["details"], "adventure_date"=>date, "price"=>number_with_precision(params[:adventure]["price"], :precision => 2), "completed"=>params[:adventure]["completed"], "paid" => false, "state"=>params[:adventure]["state"]}
        else
            temp={"number_of_people"=>params[:adventure]["number_of_people"], "action_adventure"=>params[:adventure]["action_adventure"], "country"=>params[:adventure]["country"], "city"=>params[:adventure]["city"], "description"=>params[:adventure]["description"], "details"=>params[:adventure]["details"], "price"=>number_with_precision(params[:adventure]["price"], :precision => 2), "completed"=>params[:adventure]["completed"], "paid" => false, "state"=>params[:adventure]["state"]}
        end
        if !params[:adventure]["city"]
            temp.store("city", "any location")
        end
        if !params[:adventure]["price"]
            temp["price" => 0]
        end
        @adventure = current_user.adventures.build(temp)
        if current_user.asked_actions
            variable1 = {"asked_actions" => current_user.asked_actions + 1}
        else
            variable1 = {"asked_actions" => 1}
        end
        if current_user.asked_advices
            variable2 = {"asked_advices" => current_user.asked_advices + 1}
        else
            variable2 = {"asked_advices" => 1}
        end
        if params[:adventure]["action_adventure"] == 'action'
            current_user.update_attributes!(variable1)
        else
            current_user.update_attributes!(variable2)
        end
        if current_user.save
            graph = Koala::Facebook::API.new("EAAdFTd7zE9ABACdBQuuNdfVhoBsF5cYdA6PQSvW9OlRmPRhyGRz0EUZA5BpfXZAJRAaZBp9ZCu31FHpjVZCZAnm4WvmqTvP5FxkdYLZAbJU37qxxyQ0Huqu1bqaQGnytgcYzPGAbl1PjMSBj1ZAa4ZBt4kQUVURF2ThJYVG9WJYvxBwZDZD")
            if params[:adventure]["adventure_date"] != ""
                graph.put_object(553202955027429, "feed", {
                             :name => "Test post",
                                 :message => "#{@adventure.user.first_name} from #{@adventure.user.city_of_residence}, #{@adventure.user.state} needs an #{@adventure.action_adventure} in #{@adventure.city}, #{@adventure.state}  #{@adventure.country} on #{@adventure.adventure_date.strftime("%b, %e %Y")}! #{@adventure.user.first_name} asked: \"#{@adventure.description} \". Eager to pay: $#{@adventure.price}. Invite a friend who can fulfill #{@adventure.user.first_name}'s TWIG and get $#{@adventure.price * 0.3} as a reward for invitation, or do it yourself for full reward! \n https://staging-twigs.herokuapp.com/adventures/" + "#{@adventure.id}"
                         
                             })
            else
                graph.put_object(553202955027429, "feed", {
                             :name => "Test post",
                                 :message => "#{@adventure.user.first_name} from #{@adventure.user.city_of_residence}, #{@adventure.user.state} needs an #{@adventure.action_adventure} in #{@adventure.city}, #{@adventure.state}  #{@adventure.country} any time! #{@adventure.user.first_name} asked: \"#{@adventure.description} \". Eager to pay: $#{@adventure.price}. Invite a friend who can fulfill #{@adventure.user.first_name}'s TWIG and get $#{@adventure.price * 0.3} as a reward for invitation, or do it yourself for full reward! \n. https://staging-twigs.herokuapp.com/adventures/" + "#{@adventure.id}"
                             
                             })
            end
        else
            current_user.errors.full_messages
            flash[:notice] = "Unable to create adventure. #{params[:adventure]["action_adventure"]}, #{params[:adventure]["description"]}, #{params[:adventure]["number_of_people"]},  #{params[:adventure]["city"]}"
        end
        redirect_to adventures_path
    end

    def edit
        @adventure = Adventure.find(params[:id])
        @countries = ISO3166::Country.all
    end
    
    def mytwigs
        @adventures = current_user.adventures + Adventure.where(conducted_by: current_user.id)
    end

    def update
        @adventure = Adventure.find(params[:id])
        if params[:adventure]["inviter"] != "0"
            inviter = params[:adventure]["inviter"]
            earned = number_with_precision(@adventure.price * 0.56, :precision => 2)
        else
            if @adventure.inviter != "N/A"
                inviter = @adventure.inviter
                earned = @adventure.earned
            else
                inviter = "N/A"
                earned = @adventure.earned
            end
        end
        temp={"paid" => params[:adventure][:paid], "earned" => earned, "rating" => params[:adventure][:rating], "inviter" => inviter}
        @adventure.update_attributes!(temp)
        redirect_to mytwigs_adventures_path
    end
    def destroy
        @adventure.destroy
        flash[:notice] = "Adventure deleted."
        redirect_to root_path
    end

    def correct_user
        @adventure = Adventure.find(params[:id])
        if current_user != @adventure.user
            flash[:notice] ="Sorry, you can't change other's adventures"
            redirect_to root_path
        end
    end
end

app/views/adventures/edit.html.haml
%h2 Edit Adventure
%script{:src => "https://code.jquery.com/jquery-3.1.1.min.js"}
%link{:href => "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.7/semantic.min.css", :rel => "stylesheet"}/
%script{:src => "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.7/semantic.min.js"}
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
%meta{:charset => "UTF-8"}/


= form_tag adventure_path(@adventure), :method => :put do
  -if current_user.admin
    %select{:name => "adventure[paid]"}
      %option{:value => "paid"} Paid
      %option{:value => "not paid"} Not Paid
  -else
    = hidden_field :adventure, :paid, value: @adventure.paid
  -if  @adventure.rating
    = hidden_field :adventure, :rating, value: @adventure.rating
  -else
    -if current_user.id == @adventure.user.id
      %select{:name => "adventure[rating]"}
        %option{:value => "5"} 5
        %option{:value => "4"} 4
        %option{:value => "3"} 3
        %option{:value => "2"} 2
        %option{:value => "1"} 1
  -if @adventure.inviter
    = hidden_field :adventure, :inviter, value: @adventure.inviter
  -else
    -if current_user.id != @adventure.user.id
      = number_field :adventure, :inviter, :value => 0
  = submit_tag 'Save Changes'
= link_to 'Back to adventure list', adventures_path(@adventure)

app/views/adventures/mytwigs.html.haml
:css
  .box {
    position: absolute;
    top: 165px;
    left: 352px;
    width: 660px;
    z-index: 200;
    background-color: white;
    border: 1px solid black;
    padding-left: 10px;
    padding-right: 10px;
    padding-top: 10px;
    padding-bottom: 17px;
    margin: 10px;
  }
  .mytwigs {
    text-transform: uppercase;
    font-size: 33px;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    position: absolute;
    left: 360px;
    top: 124px;
  }

  .titleline {
    clear: both;
    float:none;
    display:block;
    position: relative;
    top: 54px;
    left: 362px;
    width: 660px;
    border:none;
    border-top:1px black;
    color: black;
    background-color: black;
    height:1px;
    z-index:99;
  }

  th {
    font-size: 12px;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    border: 1px solid black;
    padding: 5px;
    width: 82.5px;
  }
  .line {
    position: absolute;
    top: -1px;
    left: -1px;
    width: 662px;
    height: 30px;
    float: left;
  }
  .line_two {
    position: relative;
    top: 18px;
    left: -11px;
    width: 662px;
    height: 30px;
    float: left;
  }
  .little_box {
    font-size: 12px;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    width: 82.5px;
    height: 30px;
    float: left;
    padding-left: 10px;
    padding-top: 5px;
  }
  .little_box2 {
    font-size: 14px;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    width: 82.5px;
    height: 30px;
    border: 1px solid black;
    float: left;
    padding-left: 10px;
    padding-top: 5px;
  }

  input[type=submit], input[type=text], input[type=file], input[type=textArea] {
    font-family: 'pproxima_nova_ltthin', sans-serif;
    color: #999997;
    -webkit-appearance: none;
    border-radius: 0;
    border: 1px solid black;
  }
  ::-webkit-input-placeholder { /* Chrome/Opera/Safari */
    color: #999997;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    font-size: 14px;
  }
  ::-moz-placeholder { /* Firefox 19+ */
    color: #999997;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    font-size: 14px;
  }
  :-ms-input-placeholder { /* IE 10+ */
    color: #999997;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    font-size: 14px;
  }
  :-moz-placeholder { /* Firefox 18- */
    color: #999997;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    font-size: 14px;
  }

.mytwigs
  MY TWIGS
.titleline
.box
  .line
    .little_box2
      Date
    .little_box2
      Form
    .little_box2
      Amount
    .little_box2
      Inviter
    .little_box2
      Earned
    .little_box2
      Rating
    .little_box2
      Status
    .little_box2
      Details


  - @adventures.sort {|a,b| b.created_at <=> a.created_at }.each do |twig|
    .line_two
      .little_box
        = local_time(twig.created_at, format: '%m/%e/%Y')
      .little_box
        - if twig.conducted_by == current_user.id
          gave #{twig.action_adventure}
        -else
          asked #{twig.action_adventure}
      .little_box
        = twig.price
      .little_box
        - if !twig.completed
          Still Pending
        - else
          -if !twig.inviter
            -if current_user.id == twig.user.id
              N/A
            -else
              = link_to("Add inviter", edit_adventure_path(twig))
          - else
            - if twig.inviter == 0
              N/A
            - else
              = link_to(User.find(twig.inviter).first_name, user_path(twig.inviter))
      .little_box
        - if !twig.completed
          Still Pending
        -else
          -if twig.user.id == current_user.id
            \- #{twig.price}
          -else
            #{twig.earned}
      .little_box
        - if !twig.completed
          Still Pending
        -else
          -if twig.rating
            = twig.rating
          -else
            -if twig.user.id == current_user.id
              = link_to("Rate", edit_adventure_path(twig))
            -else
              %td Still Pending
      .little_box
        -if twig.paid
          Paid #{twig.method}
        -else
          -if current_user.admin
            = link_to("Mark As Paid", edit_adventure_path(twig), :style => "font-size: 10px;")
          -else
            Not Paid
      .little_box
        = link_to('View', adventure_path(twig))

app/views/adventures/new.html.haml
%h2 Create New Adventure
%script{:src => "https://code.jquery.com/jquery-3.1.1.min.js"}
%link{:href => "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.7/semantic.min.css", :rel => "stylesheet"}/
%script{:src => "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.7/semantic.min.js"}
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
%meta{:charset => "UTF-8"}/

= form_tag adventures_path, :method => :post do

  = label :adventure, :number_of_people, 'I'
  = select :adventure, :number_of_people, ['Only me','+1','+2','+3','+4', '+5', 'me and more than 5 others']

  = label :adventure, :action_adventure, 'need'
  = select :adventure, :action_adventure, ['action','advice']

  = label :adventure, :country, 'in (What country are you going to?)'
  = select :adventure, :country, @countries

  = label :adventure, :city, 'What city are you going to?'
  = text_field :adventure, :city

  = label :adventure, :description, 'Ask locals anything'
  = text_area :adventure, :description

  = label :adventure, :details, 'Details'
  = text_area :adventure, :details

  #my_div.field
    = label :adventure, :adventure_date, 'choose date'
    = date_select :adventure, :adventure_date, :start_year => Date.today.year

  = label :adventure, :price, 'I am willing to offer'
  = number_field :adventure, :price

  = submit_tag 'Save Changes'
= link_to 'Back to adventure list', adventures_path