config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { registrations: 'registrations' } do
        get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
    end
    devise_scope :user do
        get '/sign-in' => "devise/sessions#new", :as => :login
    end
    get '/users/:id', :to => 'users#show', :as => :user
    resources :users, only: [:index]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :adventures do
      resources :comments
      collection do
          get 'mytwigs'
      end
    end
    resources :chat_rooms, only: [:new, :create, :show, :index] do
        post "/create_message", :to => "chat_rooms#create_msg", :as => "create_msg"
    end
    root :to => redirect('/adventures')
    resources :friendships
    resources :users
    mount ActionCable.server => '/cable'
  end

app/views/layouts/_menu.html.erb
<%= yield %>

app/views/layouts/application.html.haml
!!! 5
%html
  %script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js", :type => "text/javascript"}
  = javascript_include_tag "application"
  %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js", :type => "text/javascript"}
  %script{:src => "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js", :type => "text/javascript"}
  %script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyBjrep_jwH3Ej6ZwWhRuoDILRNt2RpElqA&callback=initMap&language=en", :type => "text/javascript"}
  %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %meta{:charset => "utf-8"}/
  %script{:src => "https://code.jquery.com/jquery-3.1.1.min.js"}
  %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :rel => "stylesheet"}/
  %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"}
  %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"}
  %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.7/semantic.min.css", :rel => "stylesheet"}/
  %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.7/semantic.min.js"}


  :css
    i.fa.fa-search {
        position: relative; !important;
        left: 100px; !important;
        z-index: 1;!important;
    }

    .inline {
        display: inline; !important;
    }
    .logostyle {
        position: relative;
        top: 66px;
        left: 361px;
        border: 1px solid white;
        color: white;
        width: 140px;
        height: 30px;
        z-index: 110;
        padding-left: 31px;
        padding-right: 31px;
        padding-top: 5px;
        padding-bottom: 5px;
    }
    .logostyle:hover {
      background-color: #414141; !important;
      color: white;
    }
    button#menu1.btn.btn-default {
      border: none;
      background-color: #2f2e2e;
      border-radius: 0px;
      cursor: pointer;
      position: relative;
      left: 978px;
      top: 35px;
    }
    .dropdown-menu.ooo {
      position: relative; !important;
      left: 600px;
    }
    .dropdown-item.some1 {
      position: relative; !important;
      left: 1100px;
      top: 30px;
      border-radius: 0px;
      border-left: 1px solid black;
      border-right: 1px solid black;
      z-index: 120;!important;
      display: block; !important;
      text-align: left; !important;
      width: 120px;
      height: 30px;
      text-decoration: none;
      background-color: white;
      color: black;
      padding-top: 10px;
      padding-left: 10px;
      font-family: 'pproxima_nova_ltthin', sans-serif;
      font-size: 12px;
    }
    .dropdown-item.some2 {
      position: relative; !important;
      left: 1100px;
      top: 30px;
      padding-top: 10px;
      border-radius: 0px;
      border-left: 1px solid black;
      border-right: 1px solid black;
      z-index: 120;!important;
      display: block; !important;
      text-align: left; !important;
      width: 120px;
      height: 30px;
      text-decoration: none;
      background-color: white;
      color: black;
      padding-left: 10px;
      font-family: 'pproxima_nova_ltthin', sans-serif;
      font-size: 12px;
    }
    .dropdown-item.some3 {
      position: relative; !important;
      left: 1100px;
      top: 30px;
      padding-top: 10px;
      border-radius: 0px;
      border-left: 1px solid black;
      border-right: 1px solid black;
      z-index: 120;!important;
      display: block; !important;
      text-align: left; !important;
      width: 120px;
      height: 30px;
      text-decoration: none;
      background-color: white;
      color: black;
      padding-left: 10px;
      font-family: 'pproxima_nova_ltthin', sans-serif;
      font-size: 12px;
    }
    .dropdown-item.some4 {
      position: relative; !important;
      left: 1100px;
      top: 30px;
      padding-top: 10px;
      border-radius: 0px;
      z-index: 120;!important;
      border-left: 1px solid black;
      border-right: 1px solid black;
      display: block; !important;
      text-align: left; !important;
      width: 120px;
      height: 30px;
      text-decoration: none;
      background-color: white;
      color: black;
      padding-left: 10px;
      font-family: 'pproxima_nova_ltthin', sans-serif;
      font-size: 12px;
    }
    .dropdown-item.some5 {
      position: relative; !important;
      left: 1100px;
      top: 30px;
      padding-top: 10px;
      padding-bottom: 10px;
      border-radius: 0px;
      border-left: 1px solid black;
      border-right: 1px solid black;
      border-bottom: 1px solid black;
      z-index: 120;!important;
      display: block; !important;
      text-align: left; !important;
      width: 120px;
      height: 40px;
      text-decoration: none;
      background-color: white;
      color: black;
      padding-left: 10px;
      font-family: 'pproxima_nova_ltthin', sans-serif;
      font-size: 12px;
    }

    .dropdown-item:hover {
      color: #999997;
      z-index: 200;
    }

    img.drpdwn {
      border: 1px solid #414141;
    }
    #drpdwn {
      position: absolute;
      left: -200px;
      border-radius: 0px;
      width: 30px;
    }
    a.messages {
      font-family: 'pproxima_nova_ltthin', sans-serif;
      position: relative; !important;
      left: 784px;
      top: 66px;
      z-index: 110;
      color: white;
      width: 140px;
      height: 30px;
      padding: 7px;
    }
    a.messages:hover {
      background-color: #414141; !important;
      color: white;
    }
    .sup{
      font-family: 'pproxima_nova_ltthin', sans-serif;
      position: relative; !important;
      left: 650px;
      top: 65px;
      width: 120px;
      height: 30px;
      cursor: pointer;
      z-index: 110;
      color: white;
      padding-top: 6px;
      padding-bottom: 6px;
      padding-left: 35px;
      padding-right: 35px;
      text-align: center;
      font-size: 14px;
      border: 1px solid #414141;
    }
    .sup:hover{
      background-color: #414141; !important;
      color: white;
    }
    .lin {
      font-family: 'pproxima_nova_ltthin', sans-serif;
      position: relative; !important;
      left: 900px;
      top: 40px;
      width: 120px;
      height: 30px;
      z-index: 110;
      color: white;
      cursor: pointer;
      text-align: center;
      padding: 7px;
      font-size: 14px;
      border: 1px solid #414141;
    }
    .lin:hover{
      background-color: #414141; !important;
      color: white;
    }

    .background {
      height: 100px;
      background: #2f2e2e;
    }
    button#menu2.btn.btn-default {
      border: none;
      background-color: #2f2e2e;
      border-radius: 0px;
      cursor: pointer;
      z-index: 110;
      position: relative;
      left: 978px;
      top: 35px;
    }
    .dropdown-menu.aaa {
      position: relative; !important;
      top: 44px;
      width: 240px;
      height: 173px;
      left: 781px;
      background-color: white;
      padding: 5px 15px;
      -webkit-appearance: none;
      margin: 5px 0;
      border-radius: 0px;
      box-sizing: border-box;
      color: black;
      resize: none;
      font-family: 'pproxima_nova_ltthin', sans-serif;
      font-size: 14px;
    }
    .useremail {
      position: relative;
      left: -6px;
      top: 4px;
      height: 30px;
      width: 220px;
      padding: 5px 15px;
      -webkit-appearance: none;
      display: inline-block;
      border: 1px solid black;
      border-radius: 0px;
      box-sizing: border-box;
      color: black;
      resize: none;
      font-family: 'pproxima_nova_ltthin', sans-serif;
      font-size: 14px;
      z-index: 100;
    }

    #userpassword {
      position: relative;
      left: -6px;
      top: 13px;
      height: 30px;
      width: 220px;
      padding: 5px 15px;
      -webkit-appearance: none;
      display: inline-block;
      border: 1px solid black;
      border-radius: 0px;
      box-sizing: border-box;
      color: black;
      resize: none;
      font-family: 'pproxima_nova_ltthin', sans-serif;
      font-size: 14px;
      z-index: 100;
    }

    #checkbox {
      position: relative;
      left: -6px;
      top: 4px;
    }

    .rememberme {
      position: relative;
      left: 10px;
      top: -14px;
      font-family: 'pproxima_nova_ltthin', sans-serif;
      font-size: 14px;
    }

    button.loginbutton {
    position: relative;
    height: 30px;
    top: -28px;
    left: -6px;
    width: 220px;
    padding: 5px 15px;
    -webkit-appearance: none;
    margin: 5px 0;
    display: inline-block;
    border: 1px solid black;
    border-radius: 0px;
    box-sizing: border-box;
    color: black;
    resize: none;
    font-family: 'pproxima_nova_ltthin', sans-serif;
    font-size: 14px;
    background-color: #d9f0fd;
    z-index: 100;
    }

    button.loginbutton:hover {
      background-color: #bee5fb;
      z-index: 100;
    }

    .forgotyour {
      position: relative;
      left: 30px;
      top: -27px;
      font-family: 'pproxima_nova_ltthin', sans-serif;
      font-size: 14px;
      color: #999997;
    }



    input[type=submit], input[type=text], input[type=file], input[type=textArea] {
      font-family: 'pproxima_nova_ltthin', sans-serif;
      color: #999997;
      -webkit-appearance: none;
      border-radius: 0;
      border: 1px solid black;
    }
    ::-webkit-input-placeholder { /* Chrome/Opera/Safari */
      color: #999997;
      font-family: 'pproxima_nova_ltthin', sans-serif;
      font-size: 14px;
    }
    ::-moz-placeholder { /* Firefox 19+ */
      color: #999997;
      font-family: 'pproxima_nova_ltthin', sans-serif;
      font-size: 14px;
    }
    :-ms-input-placeholder { /* IE 10+ */
      color: #999997;
      font-family: 'pproxima_nova_ltthin', sans-serif;
      font-size: 14px;
    }
    :-moz-placeholder { /* Firefox 18- */
      color: #999997;
      font-family: 'pproxima_nova_ltthin', sans-serif;
      font-size: 14px;
    }

    #userpassword::-webkit-input-placeholder {
      color: #999997;
      font-family: 'pproxima_nova_ltthin', sans-serif;
      font-size: 14px;
    }

    .useremail::-webkit-input-placeholder {
      color: #999997;
      padding-left: 10px;
      padding-bottom: 0px;
      font-family: 'pproxima_nova_ltthin', sans-serif;
      font-size: 14px;
    }




  %head
    %title TWIGS
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

    %body
      .background
        %a.logostyle{:href => adventures_path} T W I G S
        - if user_signed_in?
          %a.messages{:href => chat_rooms_path} Messages
          .dropdown
            %button#menu1.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
              %img{:src => "/assets/logos/user.png", :width => "30",}/
            #drpdwn.dropdown-menu.ooo{"aria-labelledby" => "dropdownMenuButton"}
              %a.dropdown-item.some1{:href => user_path(current_user.id)} MY PROFILE
              %a.dropdown-item.some2{:href => edit_user_registration_path} EDIT PROFILE
              - if current_user.admin
                %a.dropdown-item.some3{:href => users_path} USER LIST
              %a.dropdown-item.some4{:href => mytwigs_adventures_path} MY TWIGS
              %a.dropdown-item.some5{:href => destroy_user_session_path, :method => :get} LOG OUT
        - else
          %a.sup{:href => new_registration_path(resource_name)} Sign up
          .dropdown
            .lin#menu2.dropdown-toggle{"data-toggle" => "dropdown", :href => new_user_session_path} Login
            .dropdown-menu.aaa{"aria-labelledby" => "dropdownMenuButton"}
              .dropdown-item.one
                = form_tag session_path(:user) do
                  = text_field :user, :email, :class => "useremail", :placeholder => "Email"
                  = password_field :user, :password, :id => "userpassword", :placeholder => "Password"
                  %p
                  = check_box :user, :remember_me, :id => "checkbox"
                  .rememberme
                    Remember Me
                  %p
                  %button.loginbutton LOG IN
                  .forgotyour
                    = link_to "Forgot your password?", new_password_path(:user), :style => "color: black;"




    -# this goes just inside %body:
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
    = yield